on:
  repository_dispatch:
    types: [update]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Modify a Cask
        run: |
          sed -i 's/version "[0-9]+\.[0-9]+\.[0-9]+"/version "${{ github.event.client_payload.version }}"/; s/sha256 "[0-9a-f]{64}"/sha256 "${{ github.event.client_payload.sha256 }}"/' arto.rb
      - name: Commit & Push
        # https://github.com/actions/checkout/blob/main/README.md#push-a-commit-using-the-built-in-token
        run: |
          if [ -n "$(git diff --name-only arto.rb)" ]; then
            git add --update
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git commit -m "Update Cask for version ${{ github.event.client_payload.version }}"
            git push
          fi
